name: Tane Welham
favicon: null
layout_spectrum: 0.7889747286681086
typography_spectrum: 0.06589938420802355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1813889213372022
  lightness: 0.3975175516679883
  saturation: 0.6907518377993256
  rhythmicContrast: 0.18780928920023143
purpose: []
