title: Tane Welham Nuke Compositor
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#303030'
    - '#0E0E0E'
    - '#FAFAFA'
  lightness: 0.1117085
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Tane Welham
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.32425
layout_spectrum: 0.5095579
