title: Tane Welham Nuke Compositor
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0
  brandStrength: 0.5083632
  lightness: 0.1117085
  brandColors:
    - '#303030'
    - '#0E0E0E'
    - '#FAFAFA'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Tane Welham
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.06589938420802355
layout_spectrum: 0.9934289
